Fixing the failure when sourcing the environment from zsh.
A minor solution on LINUX and MAC using zsh, esp when installing Kim-API locally. 
In zsh, the value of $0 depends on the FUNCTION_ARGZERO option, which is set by default and temporarily sets the $0 to the name of the function or script when sourcing a script. To fix this problem on zsh, we can use POSIX_ARGZERO which exposes the value of $0 in spite of the current FUNCTION_ARGZERO setting.

diff --git a/utils/activate.in b/utils/activate.in
--- a/utils/activate.in
+++ b/utils/activate.in
@@ -30,17 +30,27 @@
 #
 
 #
-# Release: This file is part of the kim-api-2.1.0 package.
+# Release: This file is part of the kim-api.git repository.
 #
 
 
 # Ensure that this script is sourced, not executed
-if test x"`basename "$0" 2> /dev/null`" \
-        = x"@PROJECT_NAME@-activate"; then
-  (>&2 printf "Error:\t@PROJECT_NAME@-activate must be sourced.\n"
-   printf "\tRun 'source @PROJECT_NAME@-activate' not "
-   printf "'@PROJECT_NAME@-activate'.\n")
-  exit 1
+
+BASENAME_SOURCE=`basename -- "$0" 2> /dev/null`
+
+if test -n "$ZSH_VERSION"; then
+    if test $options[posixargzero] != "on"; then
+        setopt posixargzero
+        BASENAME_SOURCE=`basename -- "$0" 2> /dev/null`
+        setopt posixargzero
+    fi
+fi
+
+if test x"${BASENAME_SOURCE}" = x"@PROJECT_NAME@-activate"; then
+    (>&2 printf "\nError:\t@PROJECT_NAME@-activate must be sourced.\n"
+    printf "\tRun 'source @PROJECT_NAME@-activate' not "
+    printf "'@PROJECT_NAME@-activate'.\n")
+    exit 1
 fi
 
 export PATH="@CMAKE_INSTALL_FULL_BINDIR@:${PATH}"
