Print web_tool error code on failure.

diff --git a/utils/collections-management.in b/utils/collections-management.in
--- a/utils/collections-management.in
+++ b/utils/collections-management.in
@@ -46,15 +46,17 @@ make_command="make -j2"
 cmake_command="cmake"
 # determine web tool to use
 if command -v wget > /dev/null 2>&1; then
-  web_tool="wget --user-agent ${kim_user_agent} -q"
-  web_tool_query="${web_tool} -O - --post-data"
-  web_tool_url_stdin="${web_tool} -O -"
-  web_tool_download="${web_tool} --content-disposition"
+  web_tool="wget"
+  web_tool_q="${web_tool} --user-agent ${kim_user_agent} -q"
+  web_tool_query="${web_tool_q} -O - --post-data"
+  web_tool_url_stdin="${web_tool_q} -O -"
+  web_tool_download="${web_tool_q} --content-disposition"
 elif command -v curl > /dev/null 2>&1; then
-  web_tool="curl --user-agent ${kim_user_agent} -s"
-  web_tool_query="${web_tool} -o - --data"
-  web_tool_url_stdin="${web_tool} -O -"
-  web_tool_download="${web_tool} --remote-name"
+  web_tool="curl"
+  web_tool_q="${web_tool} --user-agent ${kim_user_agent} -s"
+  web_tool_query="${web_tool_q} -o - --data"
+  web_tool_url_stdin="${web_tool_q} -O -"
+  web_tool_download="${web_tool_q} --remote-name"
 else
   printf "*** ERROR *** Unable to find a web tool: please install 'wget' or 'curl'.\n";
   return 1
@@ -147,8 +149,10 @@ check_item_compatibility () {
   query="${query}"'&database=obj&history=on'
   local version
   version="`${web_tool_query} "${query}" https://query.openkim.org/api`"
-  if test $? -ne 0; then
+  local error_code=$?
+  if test ${error_code} -ne 0; then
     printf "*** ERROR *** Unable to successfully contact openkim.org to check ${item_name} compatibility.\n"
+    printf "              '${web_tool}' returned error code ${error_code}.\n"
     return 1
   fi
   version="`printf -- "%s" "${version}" | \
@@ -362,10 +366,13 @@ get_build_install_item () {
         sed -e 's/^.*\(openkim-models-.*\)\.txz.*$/\1/'`
       # download archive
       printf "Downloading..............#%s\n" "${archive_basename}" | sed -e 's/ /./g' -e 's/#/ /g'
-      if ${web_tool_download} "https://s3.openkim.org/archives/collection/${archive_basename}.txz"; then
+      ${web_tool_download} "https://s3.openkim.org/archives/collection/${archive_basename}.txz"
+      local error_code=$?
+      if test ${error_code} -eq 0; then
         tar Jxf "${archive_basename}.txz" && rm -f "${archive_basename}.txz"
       else
         printf "                Unable to download ${archive_basename}.txz from https://s3.openkim.org.\n"
+        printf "                '${web_tool}' returned error code ${error_code}.\n"
         return 1
       fi
       # configure archive
@@ -389,10 +396,13 @@ get_build_install_item () {
       if test x"" = x"${local_build_path}"; then
         if check_item_compatibility "${item_name}"; then
           printf "Downloading..............#%s\n" "${item_name}" | sed -e 's/ /./g' -e 's/#/ /g'
-          if ${web_tool_download} "https://openkim.org/download/${item_name}.txz"; then
+          ${web_tool_download} "https://openkim.org/download/${item_name}.txz"
+          local error_code=$?
+          if test ${error_code} -eq 0; then
             tar Jxf "${item_name}.txz" && rm -f "${item_name}.txz"
           else
             printf "                Unable to download ${item_name} from https://openkim.org.  Check the KIM Item ID for errors.\n"
+            printf "                '${web_tool}' returned error code ${error_code}.\n"
             return 1
           fi
         else
