Updating the get_password function
Improve the function to restore the settings and trap signals on exit.

diff --git a/utils/collections-management.in b/utils/collections-management.in
--- a/utils/collections-management.in
+++ b/utils/collections-management.in
@@ -28,6 +28,7 @@
 # Contributors:
 #    Ryan S. Elliott
 #    John S. Spear
+#    Yaser Afshar
 #
 
 #
@@ -658,43 +659,71 @@ print_list_of_items () {
   printf "\n"
 }
 
-get_password () {
-  # To be sure of reading data from the terminal no matter
-  # how output has been redirected. Must redirect stdin
-  # to the controlling terminal
-  exec < /dev/tty || return 1
-
-  # TTY current settings in a stty-readable form
-  tty_current_settings=`stty -g` || return 1
-
-  # Restore the settings on exit of the subshell or on
-  # receiving SIGINT or SIGTERM
-  trap 'stty "${tty_current_settings}"' EXIT INT TERM
-
-  # Echo input characters, and disable terminal local echo
-  stty -echo || return 1
-
-  # Redirect stdout back to /dev/tty
-  printf "Enter Password : " > /dev/tty
-
-  # Read the password
-  # The Internal Field Separator (IFS), is commonly used with read command,
-  # parameter expansions and command substitution.
-  # The 'IFS=' prefix keeps read from trimming spaces and tabs,
-  # the -r keeps it from trying to parse backslashes as escapes
-  IFS= read -r PASSWORD; exit_status=$?
-
-  # Display a newline to acknowledge the entered password
-  printf "\n" > /dev/tty
-
-  # Restore the settings now
+signal_handler() {
+  # Restore the settings on exit
   stty "${tty_current_settings}"
   trap - EXIT INT TERM
-
-  if test "${exit_status}" -ne 0; then
-    printf "*** ERROR *** Failed to read the entered password.\n"
-    return 1
+  if test x"${exit_status}" = x""; then
+    exit
+  else
+    exit_status=
   fi
+}
+
+exit_handler() {
+  local signal_exit_status
+  if test x"${exit_status}" != x""; then
+    signal_exit_status="${exit_status}"
+  else
+    signal_exit_status=$?
+  fi
+  exit_status="exit"
+  signal_handler
+  exit "${signal_exit_status}"
+}
+
+get_password () {
+  # Read the password from stdin
+  PASSWORD="$(
+    # To be sure of reading data from the terminal no matter
+    # how output has been redirected. Must redirect stdin
+    # to the controlling terminal
+    exec < /dev/tty || exit
+
+    # TTY current settings in a stty-readable form
+    tty_current_settings=`stty -g` || exit
+
+    # Restore the settings on receiving SIGINT or SIGTERM signal
+    trap 'signal_handler' INT TERM
+
+    # Restore the settings on receiving EXIT signal
+    trap 'signal_handler' EXIT
+
+    # Echo input characters, and disable terminal local echo
+    stty -echo || exit_handler
+
+    # Redirect stdout back to /dev/tty
+    printf "Enter Password : " > /dev/tty
+
+    # Read the password
+    # The Internal Field Separator (IFS), is commonly used with read command,
+    # parameter expansions and command substitution.
+    # The 'IFS=' prefix keeps read from trimming spaces and tabs,
+    # the -r keeps it from trying to parse backslashes as escapes
+    IFS= read -r password; exit_status=$?
+
+    # Display a newline to acknowledge the entered password
+    printf "\n" > /dev/tty
+
+    if test "${exit_status}" -ne 0; then
+      printf "*** ERROR *** read command failed to get the entered password. \n"
+    fi
+
+    # Return the entered password
+    printf '%s\n' "$password"
+
+    exit_handler
+  )"
 
   if !(printf -- '%s\n' "${PASSWORD}" | sudo -k -S printf "" > /dev/null 2>&1); then
     printf "Bad password.\n"
