update whitespace to conform to existing practice.

diff --git a/utils/deactivate.in b/utils/deactivate.in
--- a/utils/deactivate.in
+++ b/utils/deactivate.in
@@ -38,18 +38,18 @@
 BASENAME_SOURCE=`basename -- "$0" 2> /dev/null`
 
 if test -n "$ZSH_VERSION"; then
-    if test $options[posixargzero] != "on"; then
-        setopt posixargzero
-        BASENAME_SOURCE=`basename -- "$0" 2> /dev/null`
-        setopt posixargzero
-    fi
+  if test $options[posixargzero] != "on"; then
+    setopt posixargzero
+    BASENAME_SOURCE=`basename -- "$0" 2> /dev/null`
+    setopt posixargzero
+  fi
 fi
 
 if test x"${BASENAME_SOURCE}" = x"@PROJECT_NAME@-deactivate"; then
-    (>&2 printf "\nError:\t@PROJECT_NAME@-deactivate must be sourced.\n"
-    printf "\tRun 'source @PROJECT_NAME@-deactivate' not "
-    printf "'@PROJECT_NAME@-deactivate'.\n")
-    exit 1
+  (>&2 printf "\nError:\t@PROJECT_NAME@-deactivate must be sourced.\n"
+   printf "\tRun 'source @PROJECT_NAME@-deactivate' not "
+   printf "'@PROJECT_NAME@-deactivate'.\n")
+  exit 1
 fi
 
 export PATH=`printf "${PATH}" | sed -e "s|:@CMAKE_INSTALL_FULL_BINDIR@|:|g" \
