Convert to use standard cmake project verion vars

diff --git a/cpp/src/utils/activate.in b/cpp/src/utils/activate.in
--- a/cpp/src/utils/activate.in
+++ b/cpp/src/utils/activate.in
@@ -35,22 +35,22 @@
 
 
 _sysconfdir=@CMAKE_INSTALL_FULL_SYSCONFDIR@
-_full_package_name=@FULL_PACKAGE_NAME@
+_project_name=@PROJECT_NAME@
 
 # Ensure that this script is sourced, not executed
 if test x"`basename "$0" 2> /dev/null`" \
-        = x"${_full_package_name}-activate"; then
-  (>&2 printf "Error:\t${_full_package_name}-activate must be sourced.\n"
-   printf "\tRun 'source ${_full_package_name}-activate' not "
-   printf "'${_full_package_name}-activate'.\n")
+        = x"${_project_name}-activate"; then
+  (>&2 printf "Error:\t${_project_name}-activate must be sourced.\n"
+   printf "\tRun 'source ${_project_name}-activate' not "
+   printf "'${_project_name}-activate'.\n")
   exit 1
 fi
 
 export PATH="@CMAKE_INSTALL_FULL_BINDIR@:${PATH}"
 export PKG_CONFIG_PATH=@CMAKE_INSTALL_FULL_LIBDIR@/pkgconfig:$PKG_CONFIG_PATH
-export KIM_API_V2_CMAKE_MODULES_DIR=@CMAKE_INSTALL_FULL_LIBDIR@/@FULL_PACKAGE_NAME@/cmake/Modules
+export KIM_API_V2_CMAKE_MODULES_DIR=@CMAKE_INSTALL_FULL_LIBDIR@/@PROJECT_NAME@/cmake/Modules
 
-source "${_sysconfdir}/bash_completion.d/${_full_package_name}-completion.bash"
+source "${_sysconfdir}/bash_completion.d/${_project_name}-completion.bash"
 
 unset _sysconfdir
-unset _full_package_name
+unset _project_name
diff --git a/cpp/src/utils/deactivate.in b/cpp/src/utils/deactivate.in
--- a/cpp/src/utils/deactivate.in
+++ b/cpp/src/utils/deactivate.in
@@ -35,14 +35,14 @@
 
 
 _sysconfdir=@CMAKE_INSTALL_FULL_SYSCONFDIR@
-_full_package_name=@FULL_PACKAGE_NAME@
+_project_name=@PROJECT_NAME@
 
 # Ensure that this script is sourced, not executed
 if test x"`basename "$0" 2> /dev/null`" \
-        = x"${_full_package_name}-deactivate"; then
-  (>&2 printf "Error:\t${_full_package_name}-deactivate must be sourced.\n"
-   printf "\tRun 'source ${_full_package_name}-deactivate' not "
-   printf "'${_full_package_name}-deactivate'.\n")
+        = x"${_project_name}-deactivate"; then
+  (>&2 printf "Error:\t${_project_name}-deactivate must be sourced.\n"
+   printf "\tRun 'source ${_project_name}-deactivate' not "
+   printf "'${_project_name}-deactivate'.\n")
   exit 1
 fi
 
@@ -58,12 +58,12 @@ export PKG_CONFIG_PATH=`printf "${PKG_CONFIG_PATH}" | \
 
 unset KIM_API_V2_CMAKE_MODULES_DIR
 
-for _func in `grep "_${_full_package_name}-.*[[:space:]]*()" \
-  "${_sysconfdir}/bash_completion.d/${_full_package_name}-completion.bash"`; do
+for _func in `grep "_${_project_name}-.*[[:space:]]*()" \
+  "${_sysconfdir}/bash_completion.d/${_project_name}-completion.bash"`; do
   _func=`printf "${_func}" | sed -e 's|[[:space:]]*().*||'`
   unset -f "${_func}"
 done
 
 unset _func
 unset _sysconfdir
-unset _full_package_name
+unset _project_name
