Refactor cmake build

diff --git a/cpp/src/utils/deactivate.sh.in b/cpp/src/utils/deactivate.sh.in
--- a/cpp/src/utils/deactivate.sh.in
+++ b/cpp/src/utils/deactivate.sh.in
@@ -34,23 +34,31 @@
 #
 
 
-_package_dir=###PACKAGE#DIR###
-_sysconfdir=###SYSCONFDIR###
-_full_package_name=###FULL#PACKAGE#NAME###
+_package_dir=@PACKAGE_DIR@
+_sysconfdir=@CMAKE_INSTALL_FULL_SYSCONFDIR@
+_full_package_name=@FULL_PACKAGE_NAME@
 
 # Ensure that this script is sourced, not executed
 if test x"`basename "$0" 2> /dev/null`" \
-        = x"${_full_package_name}-activate"; then
-  (>&2 printf "Error:\t${_full_package_name}-activate must be sourced.\n"
-   printf "\tRun 'source ${_full_package_name}-activate' not "
-   printf "'${_full_package_name}-activate'.\n")
+        = x"${_full_package_name}-deactivate"; then
+  (>&2 printf "Error:\t${_full_package_name}-deactivate must be sourced.\n"
+   printf "\tRun 'source ${_full_package_name}-deactivate' not "
+   printf "'${_full_package_name}-deactivate'.\n")
   exit 1
 fi
 
-export PATH="${_package_dir}/bin:${PATH}"
 
-source "${_sysconfdir}/bash_completion.d/${_full_package_name}-completion.bash"
+export PATH=`printf "${PATH}" | sed -e "s|:${_package_dir}/bin:|:|g" \
+                                    -e "s|^${_package_dir}/bin:||" \
+                                    -e "s|:${_package_dir}/bin\$||"`
 
+for _func in `grep "_${_full_package_name}-.*[[:space:]]*()" \
+  "${_sysconfdir}/bash_completion.d/${_full_package_name}-completion.bash"`; do
+  _func=`printf "${_func}" | sed -e 's|[[:space:]]*().*||'`
+  unset -f "${_func}"
+done
+
+unset _func
 unset _package_dir
 unset _sysconfdir
 unset _full_package_name
