Update build-workflows for MacOS
	use MacOS-13, MacOS-14 instead of MacOS-13-large, MacOS-14-large
	use clang++ compiler
	use gfortran-14 compiler

diff --git a/.github/workflows/build-multiplatform.yml b/.github/workflows/build-multiplatform.yml
--- a/.github/workflows/build-multiplatform.yml
+++ b/.github/workflows/build-multiplatform.yml
@@ -50,13 +50,13 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        os: [macos-13-large, macos-14-large]
+        os: [macos-13, macos-14]
         include:
-          - os: macos-13-large
+          - os: macos-13
             DISTRO: macos_ventura
             job_name: macOS Ventura 13 (debug)
 
-          - os: macos-14-large
+          - os: macos-14
             DISTRO: macos_sonoma
             job_name: macOS Sonoma 14 (debug)
 
@@ -73,6 +73,13 @@ jobs:
 
       - name: Check out repository
         uses: actions/checkout@v2
+      
+      - name: Setup Homebrew
+        run: echo "/opt/homebrew/bin" >> $GITHUB_PATH
+
+      - name: Install dependencies
+        run: |
+          brew install ccache gcc
 
       - name: Initialize ccache
         uses: actions/cache@v2
@@ -96,13 +103,24 @@ jobs:
       - name: Install ccache via homebrew
         run: brew install ccache
 
+      - name: Check compiler installation
+        run: |
+          echo "Checking Clang and GCC..."
+          which clang++ || echo "Clang++ not found"
+          which g++ || echo "G++ not found"
+          which gcc || echo "gcc not found"
+          which gfortran-14 || echo "gfortran-14 not found"
+          clang++ --version || echo "Clang++ version check failed"
+          g++ --version || echo "G++ version check failed"
+          gfortran-14 --version || echo "gfortran-14 version check failed"
+
       - name: Build KIM API, run tests
         run: |
           export PATH="/usr/local/opt/ccache/libexec:$PATH"
           export CXX17=true
-          export CXX=g++-9
-          export CC=gcc-9
-          export FC=gfortran-9
+          export CXX=clang++
+          export CC=clang
+          export FC=gfortran-14
           env
           ./scripts/ci-build-and-test
 
